// auth action constants
export const authConstants = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_FAILURE: 'LOGOUT_FAILURE',
};

// user action constants
export const userConstants = {
  USER_REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
  USER_REGISTER_FAILURE: 'USER_REGISTER_FAILURE',
  USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
};

// slot constants
export const addSlotConstants = {
  SLOT_BOOK_REQUEST: 'SLOT_BOOK_REQUEST',
  SLOT_BOOK_SUCCESS: 'SLOT_BOOK_SUCCESS',
  SLOT_BOOK_FAILURE: 'SLOT_BOOK_FAILURE',
};

// get slots data actions
export const gameSlotConstants = {
  GET_SLOTS_DATA_REQUEST: 'GET_SLOTS_DATA_REQUEST',
  GET_SLOTS_DATA_SUCCESS: 'GET_SLOTS_DATA_SUCCESS',
  GET_SLOTS_DATA_FAILURE: 'GET_SLOTS_DATA_FAILURE',
};
